name: ringggit-mae-pdf-api
region: sgp
services:
  - name: api
    github:
      repo: blinkdagger182/ringggit
      branch: main
      deploy_on_push: true
    source_dir: /mae_pdf_processing
    environment_slug: python
    run_command: uvicorn api_server:app --host 0.0.0.0 --port 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
